### ISSUE TITLE
consider adding an episode on function writing?

### ISSUE THREAD

**Issue by drmowinckels** [carpentries-incubator/targets-workshop#13]
I'm thinking something quite basic, just like the components of a function, how you specify arguments and how those are used in the function, what it returns.

There is the functions lesson in the [R swc lesson](https://swcarpentry.github.io/r-novice-gapminder/10-functions.html), but I think that one is too much again. 

Given the learners, this episode could either be skipped or breezed through if you have a room with people that already have this skill. I know we both kind of dont like lessons where episodes can be mashed together in any order or skipped on want, but I think there are exceptions, like here. Having a _short_ episode on functions in case you have people unfamiliar with them in the room, would help instructors give some functions basics without needing to ad lib.

**Comment by drmowinckels** [comment]
If i get the time this week, I'll draft something for you to have a look at, if you agree its a good idea.

**Comment by joelnitta** [comment]
That sounds great, thanks!

**Comment by joelnitta** [comment]
Closed by #14
